spring:
  application:
    name: lazuly-users
  data:
    mongodb:
      database: lazuly-profiles
  cloud:
    stream:
      default-binder: kafka
      bindings:
        input: #Es el input definido por default en Sink
          destination: newOwner
          content-type: application/json
          group: lazuly-users #Esto es lo que permite tener una cola por servicio
        output:
          destination: newUser #Nombre de la cola o topic
          content-type: application/json
app:
  host: ${HOST}
  security:
    clientkey: ${CLIENT_KEY}
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${HOST}:8761/eureka/
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
---
spring:
  profiles: developer
  data:
    mongodb:
      uri: mongodb://localhost:27017
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
app:
  secret: aidafrancoygeorgelosamo
  signing:
    key: aidafrancoygeorgelosamo
server:
  port: 8080

---
spring:
  profiles: staging
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
app:
  secret: ${INTERNAL_SECRET}
  signing:
    key: ${JWT_SECRET}
server:
  port: ${PORT}